### ISSUE TITLE
update to newer emoji version

### ISSUE THREAD

**Issue by tbussmann** [gingerbeardman/Emojipedia#15]
Where is the file gernerator/emoji.txt coming from? I'd love to update it to a more recent version of unicode / emoji but can't find the source or way of generation of that. The structure looks like [this](http://unicode.org/emoji/charts/emoji-list.html) but there is a complex html table. According to that page, production code should only rely on the official [data files](http://www.unicode.org/Public/emoji/12.0/). It would be great if the build process could be integrated with upstream unicode data.

**Comment by gingerbeardman** [comment]
The generator code lists the source of the data. It is indeed http://unicode.org/emoji/charts/emoji-list.html but you can get tab delimited text from any HTML table selecting all text of the table/page and copying to clipboard using Google Chrome. This was easier for me, initially, way back, because the data files did not yet exist or was not easily discoverable (see [this archive link](http://web.archive.org/web/20160916184835/http://unicode.org/emoji/charts/emoji-list.html)). Since then I just kept using the same copy/paste method.

**Comment by gingerbeardman** [comment]
OK, I had a few minutes to see if my code still works with the latest copy/paste data from the Emoji v12.0 HTML table — it does!

So the Dictionary has now been updated: https://github.com/gingerbeardman/Emojipedia/releases/latest/

Cheers for the friendly reminder!

**Comment by gingerbeardman** [comment]
Migrating to the Data would be best, because the current V12.0 HTML table omits variations (such as skin tone) so there are actually less entries in the Dictionary than the previous release.

**Comment by tbussmann** [comment]
Thanks for the super quick response & update and congrats for the baby! I'll send a PR if I find time to rewrite the input of the generator script.

**Comment by gingerbeardman** [comment]
I'll get round to it this week, maybe tonight. 😉
