### ISSUE TITLE
No content in popup when using look up on word "cool"

### ISSUE THREAD

**Issue by gingerbeardman** [gingerbeardman/Emojipedia#5]
Try it yourself: cool

![screen shot 2016-12-08 at 12 42 29](https://cloud.githubusercontent.com/assets/49612/21010425/e70354dc-bd43-11e6-88b4-02b9e458d298.png)

after clicking Emojipedia

![screen shot 2016-12-08 at 12 43 58](https://cloud.githubusercontent.com/assets/49612/21010456/0bdc9dc2-bd44-11e6-9b4a-a6355ee9dfae.png)

screens from trying on this page: http://www.polygon.com/tv/2016/12/8/13881068/shigeru-miyamoto-the-roots-play-the-super-mario-bros-theme

**Comment by gingerbeardman** [comment]
@diimdeep any ideas?

**Comment by poweruser82** [comment]
On OS X 10.10.5 _Smiling Face with Sunglasses_ appears

**Comment by gingerbeardman** [comment]
Hi. Thanks! Can you please post a screenshot of the look-up of the word
cool on the example page I linked above (Miyamoto feature)

Thanks!

**Comment by poweruser82** [comment]
![Default](https://cloud.githubusercontent.com/assets/325193/21081154/2ed1a73a-bfc1-11e6-8754-b21174ffecf0.png)
![After clicking altro…](https://cloud.githubusercontent.com/assets/325193/21081153/2e1006c0-bfc1-11e6-8ce5-534e8387e73a.png)

**Comment by gingerbeardman** [comment]
Thanks! This is a very strange issue.

**Comment by gingerbeardman** [comment]
@poweruser82 what language is your system set to? care to try with English and reboot? thanks!

**Comment by poweruser82** [comment]
Italian as first language, US English as second.
Setting US English as first language and after a restart, didn't change anything. The same emoji appears when I look up "cool".
Sorry for the late answer but is never easy to find a good time for a fresh restart.

**Comment by gingerbeardman** [comment]
Thanks for your help. I will continue to investigate

**Comment by vslavik** [comment]
It doesn’t seem to be related to particular words. I don’t get any Look Up result for “cool” either (or “risen”) despite others above seeing it. 

For me, If Emojipedia is the *only* dictionary enabled (incl. disabling the builtin English one), all is fine and the entry is shown. If anything else is there, nothing:

<img width="397" alt="screen shot 2017-01-14 at 18 25 49" src="https://cloud.githubusercontent.com/assets/145881/21956728/f832e8de-da86-11e6-9b9b-fc87d317540e.png">

Just a thought, but the space for a single entry is pretty limited in Look Up and when it gets larger, only a snippet is shown followed by a “more” link. Could that be the problem? At a glance, it seems plausible — the emoji alone is about as tall as the single-entry space. So maybe it gets clipped because it doesn’t fit vertically. If that’s the case, making it smaller would help (and making it smaller enough to fit the emoji *and* its description would be needed for better usability)...

**Comment by gingerbeardman** [comment]
I'm try some tests reducing the size of the emoji.

Thanks for your input!
